steps:
- bash: |
    echo 'NEXT_PUBLIC_URL_SPID_LOGIN: $NEXT_PUBLIC_URL_SPID_LOGIN'
    echo 'NEXT_PUBLIC_API_BASE_URL: $NEXT_PUBLIC_API_BASE_URL'
    echo 'NEXT_PUBLIC_API_BASE_PATH: $NEXT_PUBLIC_API_BASE_PATH'
    yarn run generate
    yarn run build:prod
  env:
    NEXT_PUBLIC_URL_SPID_LOGIN: $(TF_PUBLIC_URL_SPID_LOGIN)
    NEXT_PUBLIC_JWT_SPID_LEVEL_VALUE_L1: $(TF_PUBLIC_JWT_SPID_LEVEL_VALUE_L1)
    NEXT_PUBLIC_JWT_SPID_LEVEL_VALUE_L2: $(TF_PUBLIC_JWT_SPID_LEVEL_VALUE_L2)
    NEXT_PUBLIC_JWT_SPID_LEVEL_VALUE_L3: $(TF_PUBLIC_JWT_SPID_LEVEL_VALUE_L3)
    NEXT_PUBLIC_API_BASE_URL: $(TF_PUBLIC_API_BASE_URL)
    NEXT_PUBLIC_API_BASE_PATH: $(TF_PUBLIC_API_BASE_PATH)
    NEXT_PUBLIC_API_FETCH_TIMEOUT: $(TF_PUBLIC_API_FETCH_TIMEOUT)
    NEXT_PUBLIC_API_FETCH_MAX_RETRY: $(TF_PUBLIC_API_FETCH_MAX_RETRY)
    NEXT_PUBLIC_FEATURE_FLAG: $(TF_PUBLIC_SESSION_LIST_FF)
    NEXT_PUBLIC_SPID_CIE_ENTITY_ID: $(TF_PUBLIC_CIE_ENTITY_ID)
    NEXT_PUBLIC_ANALYTICS_ENABLE: $(TF_PUBLIC_ANALYTICS_ENABLE) 
    NEXT_PUBLIC_ANALYTICS_MOCK: $(TF_PUBLIC_ANALYTICS_MOCK)  
    NEXT_PUBLIC_ANALYTICS_API_HOST: $(TF_PUBLIC_ANALYTICS_API_HOST)    
    NEXT_PUBLIC_ANALYTICS_PERSISTENCE: $(TF_PUBLIC_ANALYTICS_PERSISTENCE)
    NEXT_PUBLIC_ANALYTICS_LOG_IP: $(TF_PUBLIC_ANALYTICS_LOG_IP)
    NEXT_PUBLIC_ANALYTICS_DEBUG: $(TF_PUBLIC_ANALYTICS_DEBUG)
    NEXT_PUBLIC_SPID_TEST_ENV_ENABLED: $(TF_PUBLIC_SPID_TEST_ENV_ENABLED)
    NEXT_PUBLIC_SPID_TEST_ENV_UAT_ENABLED: 'true'
    NEXT_PUBLIC_CIE_UAT_LOGIN_ENABLED: 'true'
    NEXT_PUBLIC_FOOTER_PRODUCT_LIST: $(TF_PUBLIC_FOOTER_PRODUCT_LIST)
    NEXT_PUBLIC_ANALYTICS_TOKEN: $(TF_PUBLIC_ANALYTICS_TOKEN)
  displayName: 'Build Static Site'
