steps:
- bash: |
    echo 'NEXT_PUBLIC_URL_SPID_LOGIN: $NEXT_PUBLIC_URL_SPID_LOGIN'
    echo 'NEXT_PUBLIC_URL_IO: $NEXT_PUBLIC_URL_IO'
    echo 'NEXT_PUBLIC_JWT_SPID_LEVEL_VALUE_L1: $NEXT_PUBLIC_JWT_SPID_LEVEL_VALUE_L1'
    echo 'NEXT_PUBLIC_JWT_SPID_LEVEL_VALUE_L2: $NEXT_PUBLIC_JWT_SPID_LEVEL_VALUE_L2'
    echo 'NEXT_PUBLIC_JWT_SPID_LEVEL_VALUE_L3: $NEXT_PUBLIC_JWT_SPID_LEVEL_VALUE_L3'
    yarn run generate
    yarn run build
  env:
    NEXT_PUBLIC_URL_SPID_LOGIN: $(TF_PUBLIC_URL_SPID_LOGIN)
    NEXT_PUBLIC_URL_IO: $(TF_PUBLIC_URL_IO)
    NEXT_PUBLIC_JWT_SPID_LEVEL_VALUE_L1: $(TF_PUBLIC_JWT_SPID_LEVEL_VALUE_L1)
    NEXT_PUBLIC_JWT_SPID_LEVEL_VALUE_L2: $(TF_PUBLIC_JWT_SPID_LEVEL_VALUE_L2)
    NEXT_PUBLIC_JWT_SPID_LEVEL_VALUE_L3: $(TF_PUBLIC_JWT_SPID_LEVEL_VALUE_L3)
  displayName: 'Build Static Site'
