'use client';
import type { Metadata } from 'next';
import { ThemeProvider } from '@emotion/react';
import { theme } from '@pagopa/mui-italia';
import Header from '@/component/header/header';
import Footer from '@/component/footer/footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ThemeProvider theme={theme}>
      <html lang="en">
        <body>
          <Header />
          {children}
          <Footer loggedUser={false} />
        </body>
      </html>
    </ThemeProvider>
  );
}
