name: Release Infrastructure

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "infra/resources/**"
      # Terraform version edit
      - ".terraform-version"

jobs:
  release_prod:
    uses: pagopa/dx/.github/workflows/infra_apply.yaml@8ec64257f46bb8c03509d317b42fbf6a2da2c63a # main
    name: Release Infrastructure
    secrets: inherit
    with:
      environment: prod
      base_path: infra/resources
      override_github_environment: "infra-prod"
      use_private_agent: false
