name: Terraform Validation

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    paths:
      - infra/**
      - .terraform-version
      - .pre-commit-config.yaml
      - .trivyignore

jobs:
  tf_analysis:
    # Don't run in Changeset PRs
    if: ${{ github.actor != 'github-actions[bot]' }}
    uses: pagopa/dx/.github/workflows/static_analysis.yaml@733af875ece52e5fd593f013ea9abf9a8d32d1d1
    name: Terraform Validation
    secrets: inherit
    with:
      enable_modified_files_detection: true
