
name: Static Check

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "!infra/**"
      - "!.terraform-version"
      - "!.pre-commit-config.yaml"
      - "!.trivyignore"

  workflow_call:

jobs:
  checks:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-pr-staticcheck-${{ github.head_ref || github.run_id }}
      cancel-in-progress: true
    steps:
      - id: checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - id: setup
        uses: ./.github/actions/setup-composite
      - id: run-tsc
        run: yarn tsc --noemit
      - id: run-lint
        run: yarn lint --fix
      - id: test
        run: yarn test
